### ISSUE TITLE
Ruby not using all configuration keys?

### ISSUE THREAD

**Issue by brandoncc** [Pocco81/DAPInstall.nvim#10]
Hello,

Thanks for this awesome plugin!

I have the following configuration:

```ruby
dap_install.config('ruby_vsc_dbg', {
  configurations = {
    {
      name = "Run RSpec until the next failure";
      type = "ruby";
      request = "launch";
      cwd = "${workspaceFolder}";
      useBundler = true;
      pathToBundler = "/Users/brandoncc/.asdf/shims/bundle";
      pathToRDebugIDE = "/Users/brandoncc/.asdf/shims/rdebug-ide";
      showDebuggerOutput = true;
      program = "${workspaceFolder}/bin/rspec";
      args = { "--next-failure" };
    }
  }
})
```

However, this is my applied configuration:

```ruby
{
  config = {
    adapters = {
      args = { "/Users/brandoncc/.local/share/nvim/dapinstall/ruby_vsc_dbg/extension/dist/debugger/main.js" },
      command = "node",
      type = "executable"
    },
    configurations = { {
        args = { "--next-failure" },
        name = "Run RSpec until the next failure",
        program = "${workspaceFolder}/bin/rspec",
        request = "launch",
        type = "ruby"
      } }
  },
  dap_info = {
    name_adapter = "ruby",
    name_configuration = "ruby"
  },
  installer = {
    before = "",
    install = "        wget https://github.com/rubyide/vscode-ruby/releases/download/v0.25.0/ruby-0.25.0.vsix\n        mv rub
y-0.25.0.vsix ruby-0.25.0.zip\n        unzip ruby-0.25.0.zip\n        printf \"\\n\\n\\n\"\n        echo 'Do not forget to ad
d `ruby-debug-ide` gem to your bundle or system!'\n    ",
    uninstall = "simple"
  }
}
```

Do the missing configuration keys need to be whitelisted? [Here](https://github.com/rubyide/vscode-ruby/blob/da0d5d4d8d5b2d3ed3b57112e7e32a3645ef7da6/packages/vscode-ruby-client/package.json#L602-L667) is the documentation for the configuration keys.

**Comment by Pocco81** [comment]
Hey! so the author of vscode-ruby himself, @rafcamlet, added this debugger through the PR #5. I must admit, I've never used it myself but since the code was clean and the project itself had 1k back then, I marked it as "Tested" ([original comment](https://github.com/Pocco81/DAPInstall.nvim/pull/5)).

He mentioned that:

> Provided configuration is designed for working with simple scripts or small programs, but won't work with Rails applications - rails apps are the main commercial use of ruby. Maybe we should provide multiple configurations or some kind of help/instructions? Are such things outside the scope of this plugin?

So I assume that there are some other settings that must be tweaked externally for this debugger to work. With the help of @rafcamlet, I think we could make a full integration with debuggers outside of nvim-dap's scope to be installed and handled through DAPInstall.nvim, because for now, as he mentioned:

>  **I've never seen multiple default configs (in dap or vimspector wikis).**

**Comment by brandoncc** [comment]
@Pocco81 thanks for the response. I'd be happy to pitch in where I can to make this happen. I'd love to be able to debug my rspec tests (that is what I'm trying to do here). [Here](https://stackoverflow.com/questions/61961294/how-to-get-rspec-working-with-debugger-ide-in-vscode) is a SO post about it. I really don't think it would be that hard to get it working...but what do I know 😂

**Comment by Pocco81** [comment]
Perhaps [the official debugger](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ruby) supported by nvim-dap might work for you as well?

**Comment by brandoncc** [comment]
That looks really promising, I will try that today and let you know. Thank you 👍

**Comment by Pocco81** [comment]
I was looking at [all the debug adapter protocols](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/) because according to nvim-dap's repo, they should all work and the ruby one is in the list, but not in their wiki! Which means that everything should technically work.

DAPInstall.nvim is just an installer and passes whatever you pass to `dap_install.config(<dbg>, <conf>)` to nvim dap. Which means that IF some/all keys are not being passed properly then that means it's an nvim-dap issue. Maybe you could try installing and configuring it manually to discard it from being a DAPInstall.nvim issue?

**Comment by brandoncc** [comment]
Interesting, I'll try that as well. I'll report back on both.

**Comment by brandoncc** [comment]
I give up, I'll just stick with pry/byebug because I don't understand how to use dap. Thanks for the help, sorry I don't want to continue trying to make it work.

**Comment by Pocco81** [comment]
No worries. However, I think I'll still add the ruby debugger anyways :+1: . Thanks for trying! I appreciate that.

**Comment by rafcamlet** [comment]
Hi @brandoncc ! Your configuration is fine (small tip: you don't need to specify path to rdebug if you use `useBundler`). I've check and it works. And you are right! The configuration keys are filtered. I've never noticed that, because I was passing configuration directly to nvim-dap. 

@Pocco81 I think that this check is unnecessary: https://github.com/Pocco81/DAPInstall.nvim/blob/main/lua/dap-install/init.lua#L41

I don't see any reason why we shouldn't allow users to pass anything they want to dap configure. Actually, I would suggest replacing these iterations over settings keys with the `tbl_extend` for example.

----

And I'm still thinking about adding some more sample configurations or maybe a wiki page? There are like three different ways to setup dap to work with ruby code. For single scripts, rails and rspec.

**Comment by Pocco81** [comment]
> @Pocco81 I think this check is unnecessary: https://github.com/Pocco81/DAPInstall.nvim/blob/main/lua/dap-install/init.lua#L41

> I don't see any reason why we shouldn't allow users to pass anything they want to dap configure. Actually, I would suggest replacing these iterations over settings keys with the tbl_extend for example.

First of all, my bad! I thought every debugger had a `adapters = {}` and a `configurations = {}`, because that's what I saw in nvim-dap's wiki.

I don't think we need `tbl_extend for this`. So, what if users just passed the config directly to nvim-dap (as you said) but through DAPInstall? This would be useful for those that just want the defaults. In that way leaving it empty or nil would pass the default config. And of course for those that do pass a config it would get to nvim-dap directly.

This would save the iteration process. Furthermore, if users wanted to use the default config but only editing certain values, then they could pass a table with, let's say: `default_config ={ some_key = "a value I want" }`

Or maybe this last part not? What do you think @rafcamlet ?

> And I'm still thinking about adding some more sample configurations or maybe a wiki page?

For DAPInstall.nvim? Yeah we could do that. But keep in mind that nvim-dap has already done sample configs over at their wiki. But still, seems like a great idea!

**Comment by rafcamlet** [comment]
I agree. :) I will just point one thing.

```lua
elseif (opt == "configurations") then
  if (dbg.config[opt][1][inner_opt] ~= nil) then -- not nil
    dbg.config[opt][1][inner_opt] = config[opt][1][inner_opt]
  end
else
```

So there is this condition:  `if (dbg.config[opt][1][inner_opt] ~= nil)` which means that if the default config don't have this value defined then nothing will be assigned to it. Based on your message i think you wanted `if (config[opt][1][inner_opt] ~= nil)` and now it won't overwrite default settings with nils. But this line is actually unnecessary, because in lua if table has key with value nil then it is like, it doesn't exist.

For example, this piece of code will print 2 not 3.
```lua
count = 0
for k,v in pairs({a = 1, b = nil, c = 3}) do
    count = count + 1
end
print(count)
```

**Comment by brandoncc** [comment]
I agree that it seems like `tbl_extend` might be a useful tool here. I don't think I've ever seen a tool where you modify the default config instead of providing a user config that just extends the author's default config.

I love to see the progress here, and am still happy to help where I can.

**Comment by Pocco81** [comment]
Hello again! sorry for taking too long to come back to this, I was kind of busy. So,  I've decided to implement kind of the same mechanism lspinstall.nvim has, which was also discussed above: there will be the default config and user defined key and vals will be passed through the dap_install.config() func.

To simplify the part of the code that "parses" the config, I was thinking about just implementing a recursive func and that's it. Something like this would the trick:

```lua
local function replace_destination(nt_tbl, smpl_tbl)
	for key, _ in pairs(nt_tbl) do
		if (smpl_tbl[key] ~= nil) then
			if (type(nt_tbl[key]) == "table") then
				replace_destination(nt_tbl[key], smpl_tbl[key])
			else
				nt_tbl[key] = smpl_tbl[key]
			end
		end
	end
end
```

This should fix #10 and make the code more readable.

**Comment by brandoncc** [comment]
Thanks for the update. It really seems like you are reimplementing tbl_extend, but if you are more comfortable with your implementation that will most likely work fine. Seems like a reasonable solution to me 🙂

**Comment by Pocco81** [comment]
I'm so blind, I knew about `tbl_extend` but not about this one. _**`tbl_deep_extend`**_ is exactly what I was implementing with that recursive function lol. Thanks @brandoncc!

**Comment by Pocco81** [comment]
As discussed, here is the final implementation: https://github.com/Pocco81/DAPInstall.nvim/commit/83dd152dcfe7cceb5338923d720886fbcb9304ed

However, I don't want to close the issue just yet. @brandoncc in the end did you try the ruby debugger mentioned in nvim-dap's wiki? If so, do you think it should also be added to DAPInstall.nvim?

**Comment by brandoncc** [comment]
I actually only learned about deep extend yesterday too 😂 I did try the configuration you are referring to and it gave me a different issue that I don't remember, which frustrated me. I don't understand DAP well enough to figure it out, and I didn't (and still don't) have time to learn about DAP. That's why I gave up and went back to using pry.

I'll try your fix today and let you know if it makes any difference in my original issue.

Thanks for your time on this!

**Comment by Pocco81** [comment]
I mean... I didn't do much, I just made the config more extensible and that's it hahah. The real MVP is the creator of nvim-dap! Maybe you should try opening an issue in his repo asking for help on how to configure x debugger.

For now I think I'm gonna merge that commit with `main` and close the issue :)

**Comment by brandoncc** [comment]
You fixed it :-) My original config posted above works great now:

```lua
dap_install.config('ruby_vsc_dbg', {
  configurations = {
    {
      name = "Run RSpec until the next failure";
      type = "ruby";
      request = "launch";
      cwd = "${workspaceFolder}";
      useBundler = true;
      pathToBundler = "/Users/brandoncc/.asdf/shims/bundle";
      pathToRDebugIDE = "/Users/brandoncc/.asdf/shims/rdebug-ide";
      showDebuggerOutput = true;
      program = "${workspaceFolder}/bin/rspec";
      args = { "--next-failure" };
    }
  }
})
```

It is very possible I can cut some of that out such as `useBundler` as mentioned above, but I'm stoked to have it working. Thanks!
