### ISSUE TITLE
Process failed to start: no such file or directory "/bin/bash"

### ISSUE THREAD

**Issue by ITHDevelopment** [Pocco81/DAPInstall.nvim#26]
OS: Windows 10
Steps to reproduce:
Install the plugin using packer
Set up following the docs: 
```lua
local dap_install = require("dap-install")

dap_install.setup({
	installation_path = vim.fn.stdpath("data") .. "/dapinstall/",
})
```
Run <cmd>DIInstall <lang>
output: 
Vim:E903: Process failed to start: no such file or directory: "/bin/bash" function: builtin#18 Vim:E903: Process failed to start: no such file or directory: "/bin/bash"

**Comment by Pocco81** [comment]
Currently DAPInstall does not support Windows, only *.nix systems (Linux, MacOS, ...). I'll for on this for sure, but keep in mind that porting the installer script will the while...

**Comment by ITHDevelopment** [comment]
Perfect, just consider specifying the os requirements in the readme.

**Comment by Pocco81** [comment]
> just consider specifying the os requirements in the readme.

I added the [Caveats](https://github.com/Pocco81/DAPInstall.nvim/tree/main#-caveats) section.

So, I'm closing this issue because the issue it self (related with the shell) was fixed + a bunch of improvements and other bug fixes came with this. Now, elephant in the room: support for Windows. I'll be working on this when possible but for now the warning on the README about it only working on *nix systems and with Windows through WSL works _well_.
