### ISSUE TITLE
Codebase discussion

### ISSUE THREAD

**Issue by kozer** [Pocco81/DAPInstall.nvim#29]
During the implementation of `vscode-chrome-debug` I noticed something that got me confused.
In `debuggers_list.lua` there is the following structure:
```
M.debuggers = {
	["python"] = { "python" },
	["go"] = { "go" },
	["lua"] = { "lua" },
	["markdown"] = { "markdown" },
	["jsnode"] = { "javascript" },
	["php"] = { "php" },
	["dnetcs"] = { "cs" },
	["go_delve"] = { "go" },
	["ccppr_lldb"] = { "c", "cpp", "cpp_matchup", "rust" },
	["ccppr_vsc"] = { "c", "cpp", "cpp_matchup", "rust" },
	["dart"] = { "dart" },
	["ruby_vsc"] = { "ruby" },
}
```
At first, I thought that the values of this table are being used in order to add the configuration of each debugger for each of the above languages.
But I noticed that this is not the case, and actually what is being done is that in the `load` function we use `dap_info` property that exists in each adapter.
So, what is the purpose of the above values? Am I missing something here?
Thanks.

**Comment by Pocco81** [comment]
The file `debuggers_list.lua` (AKA the codebase), tracks the existing debuggers. This list is used for:
+ Asserting if a debugger passed to `:DIInstall` exists
+ Cli completion so that the list of debuggers appear when you press <tab> on the install command
+ Same as point number one but for uninstalling a debugger
+ Keeping track of the debuggers'
+ The current keys hold the name of the debuggers and the values hold the filetypes they work for. Right now the values are not used for anything, but in the future I'm planning on using them to implement some sort of "lazy loading" for the debuggers.
